### ISSUE TITLE
Settings should depend on the portfolio

### ISSUE THREAD

**Issue by benel** [Hypertopic/Porphyry#371]
### Description

Porphyry is multi-tenant. That means that a single installation is needed for multiple sites (portfolios).

For example, vitraux.porphyry.org, vases.porphyry.org, skills.porphyry.org, dessins.porphyry.org... uses the same installation.

In this kind of set-up, the configuration file looks like this: 

```yaml
services:
  - https://argos.utt.fr
  - https://steatite.utt.fr
disqus: <DISQUS_KEY>
interactiveMap: <GOOGLE_KEY>
```

#### What is the valuable outcome that cannot be achieved because of this bug?

Different portfolios: 
- need or doesn't need discussions, 
- if they need discussions, they need different moderators,
- need or doesn't need maps,
- if they need map, they might need different settings for maps (e.g. additional layers),
- need or doesn't need picture management (with Steatite).

#### For which stakeholder (people, role, project, domain) is it important?

@Hypertopic/if05-p21 Is that needed for your project?

#### Phase 1
- [ ] Scenarios (Gherkin)
- [ ] Implementation strategy

#### Phase 2
- [ ] Acceptance tests (Capybara)
- [ ] Implementation
